server.port: 37100

logging.level.org.springframework.web: DEBUG

handlebars.enabled: true
handlebars.prefix: classpath:templates/
handlebars.suffix: .hbs
handlebars.cache: false
handlebars.registerMessageHelper: true
handlebars.failOnMissingFile: false
handlebars.bindI18nToMessageSource: false
handlebars.prettyPrint: false
handlebars.infiniteLoops: false
handlebars.resolver.javaBean: true
handlebars.resolver.map: true
handlebars.resolver.method: true
handlebars.resolver.field: true