server.port: 37100

logging.level.org.springframework.web: DEBUG

handlebars.enabled: true
handlebars.prefix: classpath:templates/
handlebars.suffix: .hbs
handlebars.cache: false
handlebars.registerMessageHelper: true
handlebars.failOnMissingFile: false
handlebars.bindI18nToMessageSource: false
handlebars.prettyPrint: false
handlebars.infiniteLoops: false
handlebars.resolver.javaBean: true
handlebars.resolver.map: true
handlebars.resolver.method: true
handlebars.resolver.field: true

spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8&connectTimeout=3000&socketTimeout=10000"
spring.datasource.username: root
spring.datasource.password: rootroot
spring.datasource.driver-class-name: com.mysql.jdbc.Driver